openapi: 3.0.0
info:
  title: My Express API
  description: A simple API documentation example
  version: "1.0.0"
servers:
  - url: http://localhost:3000
  - url: https://api.example.com 
paths:
  /users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /users/{id}:
    get:
      summary: Get a user by ID
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: './schema/users.schema.js'
      responses:
        '200':
          description: A user object
